# {{ if default false .Values.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snikket-monitor
spec:
  namespaceSelector:
    matchNames: [default]
  selector:
    matchLabels:
      app: snikket
      component: server
  endpoints:
    - port: xmppd-http
      path: /metrics
      interval: 30s

# {{ end  }}
